export interface Subject {
  id: number;
  name: string;
  parentId?: number; // Optional, for sub-categories
}

export interface Book {
  id: number;
  title: string;
  authorId: number; // Foreign key to Author
  subjectIds: number[]; // Foreign key to Subject
  year: number;
  pages?: number;
  isRead: boolean;
  rating?: number; // 1-5
  coverImageUrl?: string;
  description?: string;
}

export interface Lecture {
  id: number;
  title: string;
  speakerId: number; // Foreign key to Author
  subjectIds: number[]; // Foreign key to Subject
  year: number;
  duration?: number; // In minutes
  link?: string; // URL to video/audio
}

export interface Author {
  id: number;
  name: string;
  yearOfBirth?: number;
  yearOfDeath?: number;
  countryId?: number; // Foreign key to Nation
  description?: string;
  imageUrl?: string;
  link?: string;
  subjectIds?: number[];
}

export interface Nation {
  id: number;
  name: string;
  beginYear?: number;
  endYear?: number;
  description?: string;
  imageUrl?: string;
  link?: string; // URL to Wikipedia page
  authorIds?: number[];
  civilizationId?: number;
  eraIds?: number[];
}

export interface Civilization {
  id: number;
  name: string;
  nationIds?: number[];
  description?: string;
  parentId?: number;
}

export interface Era {
  id: number;
  name: string;
  beginYear?: number;
  endYear?: number;
  description?: string;
  civilizationId?: number;
}

export interface Note {
  id: number;
  parentId: number; // ID of the Book or Lecture
  parentType: 'book' | 'lecture'; // Discriminator
  content: string;
  timestamp: string; // ISO 8601 string
}

export interface Comment {
  id: number;
  parentId: number;
  parentType: 'book' | 'lecture';
  content: string;
  timestamp: string;
  // userId?: number; // Optional, if you add user authentication
}

// DTOs for requests (Data Transfer Objects)
// Example for creating a new book (ID is generated by DB)
export type NewBook = Omit<Book, 'id'>;
export type UpdateBook = Partial<Omit<Book, 'id'>>; // For partial updates

// DTOs for other entities
export type NewSubject = Omit<Subject, 'id'>;
export type UpdateSubject = Partial<Omit<Subject, 'id'>>;

export type NewLecture = Omit<Lecture, 'id'>;
export type UpdateLecture = Partial<Omit<Lecture, 'id'>>;

export type NewAuthor = Omit<Author, 'id'>;
export type UpdateAuthor = Partial<Omit<Author, 'id'>>;

export type NewNation = Omit<Nation, 'id'>;
export type UpdateNation = Partial<Omit<Nation, 'id'>>;

export type NewCivilization = Omit<Civilization, 'id'>;
export type UpdateCivilization = Partial<Omit<Civilization, 'id'>>;

export type NewEra = Omit<Era, 'id'>;
export type UpdateEra = Partial<Omit<Era, 'id'>>;

export type NewNote = Omit<Note, 'id'>;
export type UpdateNote = Partial<Omit<Note, 'id'>>;

export type NewComment = Omit<Comment, 'id'>;
export type UpdateComment = Partial<Omit<Comment, 'id'>>;

export type KnowledgeItemKind =
  | 'book'
  | 'lecture'
  | 'article'
  | 'essay'
  | 'video'
  | 'podcast'
  | 'course'
  | 'artifact';

export type KnowledgeItemStatus = 'inbox' | 'queued' | 'active' | 'completed' | 'archived';

export interface KnowledgeItem {
  id: number;
  kind: KnowledgeItemKind;
  title: string;
  creator?: string;
  sourceName?: string;
  sourceUrl?: string;
  summary?: string;
  description?: string;
  publishedYear?: number;
  startedOn?: string;
  completedOn?: string;
  status: KnowledgeItemStatus;
  rating?: number;
  coverImageUrl?: string;
  metadata?: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
}

export interface Topic {
  id: number;
  name: string;
  slug: string;
  description?: string;
  parentTopicId?: number;
  color?: string;
  createdAt: string;
  updatedAt: string;
}

export type KnowledgeRelationType =
  | 'about'
  | 'related_to'
  | 'influenced_by'
  | 'part_of'
  | 'located_in'
  | 'during'
  | 'references';

export interface KnowledgeRelation {
  id: number;
  fromEntityType: string;
  fromEntityId: number;
  toEntityType: string;
  toEntityId: number;
  relationType: KnowledgeRelationType;
  note?: string;
  createdAt: string;
}

export type KnowledgeTaskStatus = 'todo' | 'doing' | 'done' | 'archived';

export interface KnowledgeNote {
  id: number;
  knowledgeItemId: number;
  content: string;
  createdAt: string;
  updatedAt: string;
}

export interface KnowledgeTask {
  id: number;
  knowledgeItemId: number;
  title: string;
  details?: string;
  status: KnowledgeTaskStatus;
  dueAt?: string;
  scheduledFor?: string;
  completedAt?: string;
  sortOrder?: number;
  createdAt: string;
  updatedAt: string;
}

export interface KnowledgeReview {
  id: number;
  knowledgeItemId: number;
  score?: number;
  summary?: string;
  body?: string;
  createdAt: string;
  updatedAt: string;
}

export type ActivityEventType =
  | 'knowledge_item_created'
  | 'knowledge_item_updated'
  | 'topic_created'
  | 'note_created'
  | 'task_created'
  | 'review_created'
  | 'task_completed'
  | 'exhibit_published';

export interface ActivityEvent {
  id: number;
  type: ActivityEventType;
  entityType: string;
  entityId: number;
  message: string;
  metadata?: Record<string, unknown>;
  occurredAt: string;
}

export interface Place {
  id: number;
  name: string;
  latitude?: number;
  longitude?: number;
  bounds?: Record<string, unknown>;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export interface TimelineEvent {
  id: number;
  title: string;
  startYear?: number;
  endYear?: number;
  placeId?: number;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Exhibit {
  id: number;
  title: string;
  slug: string;
  summary?: string;
  description?: string;
  isPublished: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface KnowledgeProgressSummary {
  total: number;
  active: number;
  completed: number;
  byStatus: Record<KnowledgeItemStatus, number>;
}

export const summarizeKnowledgeProgress = (
  items: Array<Pick<KnowledgeItem, 'status'>>
): KnowledgeProgressSummary => {
  const byStatus: Record<KnowledgeItemStatus, number> = {
    inbox: 0,
    queued: 0,
    active: 0,
    completed: 0,
    archived: 0,
  };

  for (const item of items) {
    byStatus[item.status] += 1;
  }

  return {
    total: items.length,
    active: byStatus.active,
    completed: byStatus.completed,
    byStatus,
  };
};

export const slugifyTopicName = (value: string) =>
  value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

export type NewKnowledgeItem = Omit<KnowledgeItem, 'id' | 'createdAt' | 'updatedAt'>;
export type UpdateKnowledgeItem = Partial<Omit<KnowledgeItem, 'id' | 'createdAt' | 'updatedAt'>>;

export type NewTopic = Omit<Topic, 'id' | 'createdAt' | 'updatedAt'>;
export type UpdateTopic = Partial<Omit<Topic, 'id' | 'createdAt' | 'updatedAt'>>;

export type NewKnowledgeRelation = Omit<KnowledgeRelation, 'id' | 'createdAt'>;
export type UpdateKnowledgeRelation = Partial<Omit<KnowledgeRelation, 'id' | 'createdAt'>>;

export type NewKnowledgeTask = Omit<KnowledgeTask, 'id' | 'createdAt' | 'updatedAt'>;
export type UpdateKnowledgeTask = Partial<Omit<KnowledgeTask, 'id' | 'createdAt' | 'updatedAt'>>;

export type NewKnowledgeNote = Omit<KnowledgeNote, 'id' | 'createdAt' | 'updatedAt'>;
export type UpdateKnowledgeNote = Partial<Omit<KnowledgeNote, 'id' | 'createdAt' | 'updatedAt'>>;

export type NewKnowledgeReview = Omit<KnowledgeReview, 'id' | 'createdAt' | 'updatedAt'>;
export type UpdateKnowledgeReview = Partial<Omit<KnowledgeReview, 'id' | 'createdAt' | 'updatedAt'>>;

export type NewActivityEvent = Omit<ActivityEvent, 'id' | 'occurredAt'>;
export type UpdateActivityEvent = Partial<Omit<ActivityEvent, 'id' | 'occurredAt'>>;

export type NewPlace = Omit<Place, 'id' | 'createdAt' | 'updatedAt'>;
export type UpdatePlace = Partial<Omit<Place, 'id' | 'createdAt' | 'updatedAt'>>;

export type NewTimelineEvent = Omit<TimelineEvent, 'id' | 'createdAt' | 'updatedAt'>;
export type UpdateTimelineEvent = Partial<Omit<TimelineEvent, 'id' | 'createdAt' | 'updatedAt'>>;

export type NewExhibit = Omit<Exhibit, 'id' | 'createdAt' | 'updatedAt'>;
export type UpdateExhibit = Partial<Omit<Exhibit, 'id' | 'createdAt' | 'updatedAt'>>;
