export interface Subject {
  id: number;
  name: string;
  parentId?: number; // Optional, for sub-categories
}

export interface Book {
  id: number;
  title: string;
  author: string;
  subjectId: number; // Foreign key to Subject
  year: number;
  pages?: number;
  isRead: boolean;
  rating?: number; // 1-5
  coverImageUrl?: string;
  description?: string;
}

export interface Lecture {
  id: number;
  title: string;
  speaker: string;
  subjectId: number; // Foreign key to Subject
  year: number;
  duration?: number; // In minutes
  link?: string; // URL to video/audio
}

export interface Note {
  id: number;
  parentId: number; // ID of the Book or Lecture
  parentType: 'book' | 'lecture'; // Discriminator
  content: string;
  timestamp: string; // ISO 8601 string
}

export interface Comment {
  id: number;
  parentId: number;
  parentType: 'book' | 'lecture';
  content: string;
  timestamp: string;
  // userId?: number; // Optional, if you add user authentication
}

// DTOs for requests (Data Transfer Objects)
// Example for creating a new book (ID is generated by DB)
export type NewBook = Omit<Book, 'id'>;
export type UpdateBook = Partial<Omit<Book, 'id'>>; // For partial updates

// DTOs for other entities
export type NewSubject = Omit<Subject, 'id'>;
export type UpdateSubject = Partial<Omit<Subject, 'id'>>;

export type NewLecture = Omit<Lecture, 'id'>;
export type UpdateLecture = Partial<Omit<Lecture, 'id'>>;

export type NewNote = Omit<Note, 'id'>;
export type UpdateNote = Partial<Omit<Note, 'id'>>;

export type NewComment = Omit<Comment, 'id'>;
export type UpdateComment = Partial<Omit<Comment, 'id'>>; 